### ISSUE TITLE
Modularize components and i18n

### ISSUE THREAD

**Issue by gmarcos87** [Download/preact-i18nline#5]
Hello, I'm trying to modularize all my components (in different npm packages). I use preact-i18n in the current application, but how can I migrate general i18n to modular component use? Do I have to put all the logic of language detection in each module?
It is very important for this project to maintain the lowest possible weight.

Thank you very much for your excellent work!

**Comment by Download** [comment]
Hi @gmarcos87 Sorry I did not see your issue earlier. 

> Do I have to put all the logic of language detection in each module?

I put it in a middleware in Express that is at the 'top' of the route tree.

But basically, localization is usually a framework concern. What I do is in my build I generate the translation file based on the translations from all the different components in my project. So there will be one translation file (per language), so in that sense it is not modular (the output isn't). However the modules themselves can be blissfully unaware of this.

Can you maybe give a little bit more concrete example of what you are trying to achieve?

**Comment by Download** [comment]
@gmarcos87  I think I misread you in my earlier response. Sorry about that. I know see what you are saying (I think :).

This project assumes there will be a translation file generated for english and that you will (have some native speaker) translate that into all the other languages you support. So if you want to package up  (npm) modules, you would naturally end up at having a translation file per module. You would have to include `preact-i18nline` as a dev dependency in each module, but that basically means setting up a good module project once then copying it for each module.

The difficult part would be the creation/bundling of the translation file in the final application project. I think you can use Webpack (possibly using code splitting) to achieve that. You would create an entry point for the translations, then from there load all the translation files from all the modules you are importing into your app (again, possibly using code splitting if there are many) to end up at a single translation file for the entire app.
