### ISSUE TITLE
Lack in documentation

### ISSUE THREAD

**Issue by trsh** [Download/preact-i18nline#7]
I have gone trough docs again an again and having problem to find the simplest basic/things. 

a) How I define default language;
b) How I switch language;

:/

**Comment by Download** [comment]
To switch language, set the I18n.locale, like this:

```js
I18n.locale = "en-US";
```

Have a look at the [example app](https://github.com/Download/preact-i18nline/tree/1.5.0/examples/webpack) and specifically the file [i18nliner-glue.js](https://github.com/Download/preact-i18nline/blob/1.5.0/examples/webpack/i18nliner-glue.js).

I agree the docs are a bit lacking but this project is just a fork and I am not actively working on it atm. If you continue to work with preact-i18nline and have ideas to improve the documentation I would definitely welcome them.

**Comment by Download** [comment]
On a related note. I am working on a book about Progressive Web Apps with Preact right now and it will include a chapter about using Preact with Preact CLI so I'm currently testing all that and making sure I have documented how to go about it. I will update the docs once things are clear and let you know in this issue. Thanks for reporting your feedback!

**Comment by Download** [comment]
@trsh Please review the new docs! You were absolutely right. The previous docs were not clear on how to setup a project. I added a whole section on that. Hoping it helps! Please let me know.

**Comment by trsh** [comment]
@Download tnx
