### ISSUE TITLE
Can't get the translation files to generate

### ISSUE THREAD

**Issue by chinchang** [Download/preact-i18nline#9]
Followed all the steps in the readme. When I run `i18nline synch`, its just logs:

```
Synching internationalization files in /Users/chang/projects/web-maker/src/i18n
Create files here named '{locale}.json' (e.g. 'fr.json') to include them in the synching process.
```

And sits there without exiting. Do I need to do something else to make it read the source files?

**Comment by Download** [comment]
Can you list the directory contents of `/Users/chang/projects/web-maker/src/i18n`?
It should contain (initially empty) files for the languages you want to support. So if you want say French and German translations, you would create `fr.json` and `de.json` in this folder.

> sits there without exiting.

That is weird. Are the files locked in any way maybe?

It may help to point me to a repo that I can check out that demonstrates your issue.
